name: packer
on: [push]

jobs:
  packer:
    name: Create Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install QEMU
        run: sudo apt-get update && sudo apt-get install qemu-kvm qemu qemu-system-x86 && qemu-system-x86_64

      - name: Get FAUST Image
        run: ./scripts/get_image.sh

      - name: Create GCP credentials
        run: echo ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}} | base64 -d > account.json 

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: operatehappy/packer-github-actions@master
        with:
          command: fix
          target: packer.json

      # validate templates
      - name: Validate Template
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer.json

      # validate templates
      - name: Build Artifact
        uses: operatehappy/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort -var 'gcp_project_id=${{secrets.GCP_PROJECT_ID}}' -var 'team_no=${{secrets.TEAM_NO}}'"
          target: packer.json
